# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install locales for Spanish
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && echo "es_ES.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen es_ES.UTF-8
ENV LANG=es_ES.UTF-8 LC_ALL=es_ES.UTF-8

WORKDIR /app

# Copy application files
COPY server.py .

# Install Python dependencies
RUN pip install --no-cache-dir mcp

# Use stdio transport, no ports exposed
CMD ["python", "server.py"]
